/*
 * IBM Key Protect API
 *
 * IBM Key Protect helps you provision encrypted keys for apps across IBM Cloud. As you manage the lifecycle of your keys, you can benefit from knowing that your keys are secured by cloud-based FIPS 140-2 Level 2 hardware security modules (HSMs) that protect against theft of information. You can use the Key Protect API to store, generate, and retrieve your key material. Keys within the service can protect any type of data in your symmetric key based encryption solution.
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package keyprotect
import (
	"time"
)

// The response for creating a transport encryption key.
type LockerMetadata struct {
	// The v4 UUID used to uniquely identify the resource, as specified by RFC 4122.
	Id string `json:"id,omitempty"`
	// The date the transport encryption key was created. The date format follows RFC 3339.
	CreationDate time.Time `json:"creationDate,omitempty"`
	// The date the transport encryption key expires. The date format follows RFC 3339.
	ExpirationDate time.Time `json:"expirationDate,omitempty"`
	// The number of times that a transport key can be retrieved within its expiration time before it is no longer  accessible. 
	MaxAllowedRetrievals float32 `json:"maxAllowedRetrievals,omitempty"`
	// The remaining number of times the transport encryption key can be retrieved before becoming inaccessible.
	RemainingRetrievals float32 `json:"remainingRetrievals,omitempty"`
}
