/*
 * IBM Key Protect API
 *
 * IBM Key Protect helps you provision encrypted keys for apps across IBM Cloud. As you manage the lifecycle of your keys, you can benefit from knowing that your keys are secured by cloud-based FIPS 140-2 Level 2 hardware security modules (HSMs) that protect against theft of information. You can use the Key Protect API to store, generate, and retrieve your key material. Keys within the service can protect any type of data in your symmetric key based encryption solution.
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package keyprotect

// The metadata for the key algorithm.
type KeyMetadataAlgorithmMetadata struct {
	// The algorithm bit size used for key encryption.
	BitLength string `json:"bitLength,omitempty"`
	// The encryption scheme used to generate the key. Currently, GCM is supported.
	Mode string `json:"mode,omitempty"`
}
